//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menajes_Maipu.Models.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banco_menaje
    {
        public string Num_cuenta { get; set; }
        public string Nombre_cuenta { get; set; }
        public string Tipo_cuenta { get; set; }
        public string Nombre_titular { get; set; }
        public string Estado { get; set; }
    }
}
