//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menajes_Maipu.Models.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banco_menaje
    {
        public string Num_cuenta { get; set; }
        public string Nombre_cuenta { get; set; }
        public string Tipo_cuenta { get; set; }
        public string Nombre_titular { get; set; }
        public string Estado { get; set; }
    }
}
