//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menajes_Maipu.Models.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int Id_contacto { get; set; }
        public string Nombre_contacto { get; set; }
        public string Email_contacto { get; set; }
        public string Asunto_contacto { get; set; }
        public string Mensaje_contacto { get; set; }
        public string Estado { get; set; }
        public string Fecha { get; set; }
    }
}
