//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menajes_Maipu.Models.ModeloBD
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contacto
    {
        public int Id_contacto { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        [RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$", ErrorMessage =
           "Este campo solo soporta letras")]
        [StringLength(25, MinimumLength = 3, ErrorMessage = "Tamaño inválido")]
        public string Nombre_contacto { get; set; }

        [Required(ErrorMessage = "Campo Requerido")]
        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail inválido")]
        public string Email_contacto { get; set; }

   
        [Required(ErrorMessage = "Campo Requerido")]
        [RegularExpression("[a-zA-Z0-9 -]+", ErrorMessage =
           "Este campo solo soporta letras")]
        public string Asunto_contacto { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        [RegularExpression(@"^[a-zA-Z0-9''-'\s]{1,40}$", ErrorMessage =
  "Este campo solo soporta letras")]
        public string Mensaje_contacto { get; set; }
        public string Estado { get; set; }
        public string Fecha { get; set; }
    }
}
