//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menajes_Maipu.Models.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion_cart
    {
        public int Id_carrito { get; set; }
        public Nullable<int> Id_cotizacion { get; set; }
        public Nullable<int> Id_producto { get; set; }
        public Nullable<int> Precio_p { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Cotizacion Cotizacion { get; set; }
    }
}
