//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menajes_Maipu.Models.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cotizacion()
        {
            this.Cotizacion_cart = new HashSet<Cotizacion_cart>();
        }
    
        public int Id_cotizacion { get; set; }
        public string Fecha_venta { get; set; }
        public Nullable<int> Total_venta { get; set; }
        public Nullable<int> id_user { get; set; }
        public string Hora_venta { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotizacion_cart> Cotizacion_cart { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
