//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menajes_Maipu.Models.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debito
    {
        public Nullable<int> Cod_deposito { get; set; }
        public string Num_cuenta { get; set; }
        public string Fecha_deposito { get; set; }
        public int Id_ventas { get; set; }
        public string N_img { get; set; }
        public byte[] Imagen { get; set; }
    
        public virtual Ventas Ventas { get; set; }
    }
}
