//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menajes_Maipu.Models.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debito
    {
        public Nullable<int> Cod_deposito { get; set; }
        public string Num_cuenta { get; set; }
        public string Fecha_deposito { get; set; }
        public int Id_ventas { get; set; }
        public string N_img { get; set; }
        public byte[] Imagen { get; set; }
    
        public virtual Ventas Ventas { get; set; }
    }
}
