//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menajes_Maipu.Models.ModeloBD
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Despacho
    {
        public int Num_seguimiento { get; set; }
        public string Estado_despacho { get; set; }
        public string Fecha_envio { get; set; }
        public string Fecha_entrega { get; set; }
        public Nullable<int> Id_ventas { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]

        public string Calle { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
  
        public Nullable<int> Numero { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]

        public string Comuna { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]

        public string Ciudad { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        public string Cod_postal { get; set; }
        public Nullable<int> Num_departamento { get; set; }
        public int Id_despacho { get; set; }
    
        public virtual Ventas Ventas { get; set; }
    }
}
