//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menajes_Maipu.Models.ModeloBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MenajesbdEntities6 : DbContext
    {
        public MenajesbdEntities6()
            : base("name=MenajesbdEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banco_menaje> Banco_menaje { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Contacto> Contacto { get; set; }
        public virtual DbSet<Mensaje_consulta> Mensaje_consulta { get; set; }
        public virtual DbSet<Metodo_pago> Metodo_pago { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Subcategoria> Subcategoria { get; set; }
        public virtual DbSet<UserInRol> UserInRol { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Despacho> Despacho { get; set; }
        public virtual DbSet<Carrito> Carrito { get; set; }
        public virtual DbSet<Debito> Debito { get; set; }
        public virtual DbSet<Cotizacion> Cotizacion { get; set; }
        public virtual DbSet<Cotizacion_cart> Cotizacion_cart { get; set; }
    
        public virtual ObjectResult<VentaDetalle_Result> VentaDetalle(Nullable<int> id_user, Nullable<int> id_venta)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            var id_ventaParameter = id_venta.HasValue ?
                new ObjectParameter("id_venta", id_venta) :
                new ObjectParameter("id_venta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VentaDetalle_Result>("VentaDetalle", id_userParameter, id_ventaParameter);
        }
    
        public virtual ObjectResult<Cotizacion_Detalle_Result> Cotizacion_Detalle(Nullable<int> id_user, Nullable<int> id_cotizacion)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            var id_cotizacionParameter = id_cotizacion.HasValue ?
                new ObjectParameter("id_cotizacion", id_cotizacion) :
                new ObjectParameter("id_cotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cotizacion_Detalle_Result>("Cotizacion_Detalle", id_userParameter, id_cotizacionParameter);
        }
    }
}
