//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menajes_Maipu.Models.ModeloBD
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Mensaje_consulta
    {
        public int Id_contacto { get; set; }
        public string Motivo_consulta { get; set; }
        public string Estado_consuta { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        [RegularExpression(@"^[a-zA-Z0-9''-'\s]{1,40}$", ErrorMessage =
  "Este campo solo soporta letras")]
        public string Mensaje { get; set; }
        public Nullable<int> id_user { get; set; }
        public string Respuesta_consulta { get; set; }
        public string Fecha { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
