//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menajes_Maipu.Models.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje_consulta
    {
        public int Id_contacto { get; set; }
        public string Motivo_consulta { get; set; }
        public string Estado_consuta { get; set; }
        public string Mensaje { get; set; }
        public Nullable<int> id_user { get; set; }
        public string Respuesta_consulta { get; set; }
        public string Fecha { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
