//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menajes_Maipu.Models.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metodo_pago
    {
        public int Id_metodo_pago { get; set; }
        public string Tipo_mpago { get; set; }
        public Nullable<int> Id_ventas { get; set; }
        public Nullable<int> Cod_deposito { get; set; }
    
        public virtual Ventas Ventas { get; set; }
    }
}
