//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menajes_Maipu.Models.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metodo_pago
    {
        public int Id_metodo_pago { get; set; }
        public string Tipo_mpago { get; set; }
        public Nullable<int> Id_ventas { get; set; }
        public Nullable<int> Cod_deposito { get; set; }
    
        public virtual Ventas Ventas { get; set; }
    }
}
