//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menajes_Maipu.Models.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Carrito = new HashSet<Carrito>();
        }
    
        public int Id_producto { get; set; }
        public string Nombre_producto { get; set; }
        public byte[] Imagen_producto { get; set; }
        public string Descripcion_producto { get; set; }
        public Nullable<int> Stock_producto { get; set; }
        public Nullable<int> Precio_producto { get; set; }
        public int Id_subcategoria { get; set; }
        public string Nombre_imagen { get; set; }
        public Nullable<int> Tipo { get; set; }
    
        public virtual Subcategoria Subcategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carrito> Carrito { get; set; }
    }
}
