//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menajes_Maipu.Models.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInRol
    {
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_rol { get; set; }
        public int id_urol { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
