//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menajes_Maipu.Models.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInRol
    {
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_rol { get; set; }
        public int id_urol { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
