//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menajes_Maipu.Models.ModeloBD
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Mensaje_consulta = new HashSet<Mensaje_consulta>();
            this.UserInRol = new HashSet<UserInRol>();
            this.Ventas = new HashSet<Ventas>();
            this.Cotizacion = new HashSet<Cotizacion>();
        }
        [Required(ErrorMessage = "Campo Requerido")]
        [Range(0, int.MaxValue, ErrorMessage = "Numero inválido")]
        [StringLength(10, MinimumLength = 9, ErrorMessage = "Tamaño inválido")]
        public string Rut { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        [RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$", ErrorMessage =
           "Este campo solo soporta letras")]
        [StringLength(25, MinimumLength = 3, ErrorMessage = "Tamaño inválido")]
        public string Nombre_usuario { get; set; }
        [RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$", ErrorMessage =
         "Este campo solo soporta letras")]
        [Required(ErrorMessage = "Campo Requerido")]
        public string Apellido_usuario { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        public string Email_usuario { get; set; }
        [Range(0.0, Double.MaxValue)]
        public string Telefono_usuario { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        public string Contrasena { get; set; }
        public Nullable<int> Tipo { get; set; }
        public int id_user { get; set; }
        public string Sexo { get; set; }
        public string Fecha_registro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensaje_consulta> Mensaje_consulta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInRol> UserInRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas> Ventas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotizacion> Cotizacion { get; set; }
    }
}
